
service: seo-management-app

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  memorySize: 2048
  timeout: 900
  logRetentionInDays: 1
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroupIds.${self:provider.stage}}
    subnetIds: ${self:custom.subnetIds.${self:provider.stage}}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "*"
  environment:
    NODE_ENV: production
    STAGE: ${self:provider.stage}
    JS_VERSION: ${opt:jsVersion, '1.0.0'}
    MAX_AJAX_RETRIES: 2
    DATE_FORMAT: yyyy-MM-dd
    DEBUG_MODE: off
    ALLOWED_SCRIPT_SRC: ${self:custom.allowedSrc.scriptSrc.${self:provider.stage}}
    ALLOWED_CONNECT_SRC: ${self:custom.allowedSrc.connectSrc.${self:provider.stage}}
    ALLOWED_IMG_SRC: ${self:custom.allowedSrc.imgSrc.${self:provider.stage}}
    ALLOWED_FRAME_SRC: ${self:custom.allowedSrc.frameSrc.${self:provider.stage}}
    ALLOWED_OBJECT_SRC: ${self:custom.allowedSrc.objectSrc.${self:provider.stage}}
    ALLOWED_STYLE_SRC: ${self:custom.allowedSrc.styleSrc.${self:provider.stage}}
    ALLOWED_FONT_SRC: ${self:custom.allowedSrc.fontSrc.${self:provider.stage}}
    ALLOW_CORSORIGIN: ${self:custom.allowedSrc.corsOrigin.${self:provider.stage}}
    
custom:
  securityGroupIds:
    dev: sg-09369536aaa122537
    qa: sg-07070524589589625
    stage: sg-0d862bf2e1912ad0f
    prod: sg-0d862bf2e1912ad0f
  subnetIds:
    dev: 
      - subnet-03d88cd092be1469d
      - subnet-080ebc41f32dc9a85
      - subnet-018b5c6d09403d884
    qa:
      - subnet-0f1e532cf2efa30e6
      - subnet-05047ab53b26b6459
      - subnet-0cd6e2033a0e94c79
    stage:
      - subnet-0d1c318f18545454b
      - subnet-01a410c8881bbbe4d
      - subnet-0ebdfddee146f0f06
    prod:
      - subnet-0d1c318f18545454b
      - subnet-01a410c8881bbbe4d
      - subnet-0ebdfddee146f0f06
  s3Buckets:
    dev: vsts-dev-lambda-drop
    qa: vsts-dev-lambda-drop
    stage: vsts-dev-lambda-drop-mumbai
    prod: vsts-dev-lambda-drop-mumbai
  allowedSrc:
    scriptSrc:
      dev: "*.googleapis.com"
      qa: "*.googleapis.com"
      stage: "*.googleapis.com"
      prod: "*.googleapis.com"
    connectSrc:
      dev: "*.googleapis.com"
      qa: "*.googleapis.com"
      stage: "*.googleapis.com"
      prod: "*.googleapis.com"
    imgSrc:
      dev: ""
      qa: ""
      stage: ""
      prod: ""
    frameSrc:
      dev: ""
      qa: ""
      stage: ""
      prod: ""
    objectSrc:
      dev: ""
      qa: ""
      stage: ""
      prod: ""
    styleSrc:
      dev: ""
      qa: ""
      stage: ""
      prod: ""
    fontSrc:
      dev: ""
      qa: ""
      stage: ""
      prod: ""
    corsOrigin:
      dev: ""
      qa: ""
      stage: ""
      prod: ""
  
functions:
  app:
    name: ${self:provider.stage}-seo-management-app
    handler: index.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: ANY
    tags:
      LOB: TRAVEAZY
      PRODUCT: SEO

package:
  patterns:
    - '!**'
    - 'index.js'
    - 'dist/**'
    - '!dist/**/*.map'
    - '!node_modules/**'
