// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wolzqgjfiigdyfgibdiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvbHpxZ2pmaWlnZHlmZ2liZGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTM4NjIsImV4cCI6MjA1OTc2OTg2Mn0.BJH86BrYhnVFUfoKk_jHtVoUn951dz7JNOwzntkROPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);